### PR TITLE
Stopping fan when calling service stop

### PR DESCRIPTION
**Pull request by davidRetana**

### CODE REVIEW

**Comment by Pyrestone** [comment]
This will not work, as it does not stop the process.

**Comment by nicolasff** [comment]
Doing this in [ExecStop](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStop=) is incorrect since this entry takes a command used to stop the service, so as @Pyrestone pointed out, with this change the service would no longer stop.

Instead, this `echo` command could take place in [ExecStopPost](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStopPost=) (_Additional commands that are executed after the service is stopped_):

    ExecStopPost=/bin/sh -c '/bin/echo 0 > /sys/devices/pwm-fan/target_pwm'

@Pyrestone what do you think of this approach? I tested this change locally and the fan did stop when I stopped the service.

**Comment by Pyrestone** [comment]
@nicolasff Thanks for investigating this, I have inplemented the appropriate changes.

**Comment by nicolasff** [comment]
@Pyrestone great! thanks for writing this service, this is super useful.

**Pull request closed without merging**
